### ISSUE TITLE
Highlighting of bound words (if, then, else, end, etc)

### ISSUE THREAD

**Issue by ImmortalPony** [ken1882/vscode-cea-syntax-highlighting#1]
Thanks for usefull extention! Please add lua highlighting of bound words (if, then, else, end, etc) like other lua extentions do.

E.g. https://marketplace.visualstudio.com/items?itemName=sumneko.lua
![Example](https://i.imgur.com/GNoCWlZ.jpg)

**Comment by ken1882** [comment]
I just checked with one of script I made before and it works fine, it's using vscode's internal language support for lua block so please check your vscode version and whether it has built-in syntax highlighting for those keywords
![圖片](https://user-images.githubusercontent.com/15257541/159212570-7a0fe327-c04f-4065-904c-e2701db88cd7.png)

**Comment by ImmortalPony** [comment]
Sry. My bad. It works flawlessly. Thanks.
